-- This file is automatically generated by Krait.
-- Do not edit this file manually (use `krait --update-repo` instead).
krait.manifest = {
    repo = "m1ten/kraits",
    latest_commit = "ba8f679247b34e2ce3d97f60b45ceed93cf0fd3d",
    timestamp = 1673906779,
    packages = {
        ["example"] = {
            ["1"] = {
                {
                    commit = "2f250dd0ac0791d80b2793900dc6fc01bd561405",
                    path = "packages/example",
                    timestamp = 1673902802,
                    contents = {
                        {
                            name = "manifest.lua",
                            path = "packages/example/manifest.lua",
                            sha1 = "b4bd64bc84eadf9ce4dc24f5dd7f0526fbf8cd51",
                            url = "https://raw.githubusercontent.com/m1ten/kraits/2f250dd0ac0791d80b2793900dc6fc01bd561405/packages/example/manifest.lua"
                        }, {
                            name = "otherfile.txt",
                            path = "packages/example/otherfile.txt",
                            sha1 = "dd7add6d1dbba18b266231e62a3e05210d8088bf",
                            url = "https://raw.githubusercontent.com/m1ten/kraits/2f250dd0ac0791d80b2793900dc6fc01bd561405/packages/example/otherfile.txt"
                        }
                    }
                }
            },
            ["2"] = {
                {
                    commit = "1b9c9077e3f70f59ac6b587d8bdc0d99062a02e0",
                    path = "packages/example",
                    timestamp = 1673905580,
                    contents = {
                        {
                            name = "manifest.lua",
                            path = "packages/example/manifest.lua",
                            sha1 = "0f5d5852b702c31460da5063abb131ac6b956ba6",
                            url = "https://raw.githubusercontent.com/m1ten/kraits/1b9c9077e3f70f59ac6b587d8bdc0d99062a02e0/packages/example/manifest.lua"
                        }, {
                            name = "otherfile.txt",
                            path = "packages/example/otherfile.txt",
                            sha1 = "dd7add6d1dbba18b266231e62a3e05210d8088bf",
                            url = "https://raw.githubusercontent.com/m1ten/kraits/1b9c9077e3f70f59ac6b587d8bdc0d99062a02e0/packages/example/otherfile.txt"
                        }
                    }
                }, {
                    commit = "dfdcb297293d6193944bab7d1d825748cc5e0e97",
                    path = "packages/example",
                    timestamp = 1673905653,
                    contents = {
                        {
                            name = "manifest.lua",
                            path = "packages/example/manifest.lua",
                            sha1 = "0f5d5852b702c31460da5063abb131ac6b956ba6",
                            url = "https://raw.githubusercontent.com/m1ten/kraits/dfdcb297293d6193944bab7d1d825748cc5e0e97/packages/example/manifest.lua"
                        }, {
                            name = "otherfile.txt",
                            path = "packages/example/otherfile.txt",
                            sha1 = "dd7add6d1dbba18b266231e62a3e05210d8088bf",
                            url = "https://raw.githubusercontent.com/m1ten/kraits/dfdcb297293d6193944bab7d1d825748cc5e0e97/packages/example/otherfile.txt"
                        }
                    }
                }
            },
            ["3"] = {
                {
                    commit = "ba8f679247b34e2ce3d97f60b45ceed93cf0fd3d",
                    path = "packages/example",
                    timestamp = 1673906779,
                    contents = {
                        {
                            name = "manifest.lua",
                            path = "packages/example/manifest.lua",
                            sha1 = "06add5d6d1369b44703d2e29b108420182534b34",
                            url = "https://raw.githubusercontent.com/m1ten/kraits/ba8f679247b34e2ce3d97f60b45ceed93cf0fd3d/packages/example/manifest.lua"
                        }, {
                            name = "otherfile.txt",
                            path = "packages/example/otherfile.txt",
                            sha1 = "dd7add6d1dbba18b266231e62a3e05210d8088bf",
                            url = "https://raw.githubusercontent.com/m1ten/kraits/ba8f679247b34e2ce3d97f60b45ceed93cf0fd3d/packages/example/otherfile.txt"
                        }
                    }
                }
            }
        }
    }
}