-- This file is automatically generated by Krait.
-- Do not edit this file manually (use `krait --update-repo` instead).
krait.manifest = {
    repo = "m1ten/kraits",
    latest_commit = "74eaa79ecd1c35d9e85ff839ac04965c2ceb2f7b",
    timestamp = 1673842851,
    packages = {
        ["example"] = {
            ["1"] = {
                {
                    commit = "74eaa79ecd1c35d9e85ff839ac04965c2ceb2f7b",
                    path = "packages/example",
                    timestamp = 1673842851,
                    contents = {
                        {
                            name = "manifest.lua",
                            path = "packages/example/manifest.lua",
                            sha1 = "92684eb009050d0e8e6fd3706fbef3002fb2f018",
                            url = "https://raw.githubusercontent.com/m1ten/kraits/74eaa79ecd1c35d9e85ff839ac04965c2ceb2f7b/packages/example/manifest.lua"
                        }, {
                            name = "otherfile.txt",
                            path = "packages/example/otherfile.txt",
                            sha1 = "dd7add6d1dbba18b266231e62a3e05210d8088bf",
                            url = "https://raw.githubusercontent.com/m1ten/kraits/74eaa79ecd1c35d9e85ff839ac04965c2ceb2f7b/packages/example/otherfile.txt"
                        }
                    }
                }
            }
        }
    }
}
