name = [ "test" ]
ver = "1.2.3"
desc = "test package"
license = [ "Public Domain" ]

[[pkg]]
repos = [
  "abc://test.xyz/test/repo",
  "abc://test.xyz/test/repo-mirror"
]
ver = "1.2.3"
type = "binary"

  [[pkg.supports]]
  x86 = [ "ubuntu", "arch" ]

  [[pkg.supports]]
  x86_64 = [ "windows", "darwin" ]

  [[pkg.deps]]
  test-2 = "4.5.6"

  [[pkg.deps]]
  test-3 = "7.8.9"

  [[pkg.dev_deps]]
  test-4 = "6.9.0"

  [[pkg.dev_deps]]
  test-5 = "4.2.0"

  [[pkg.srcs]]
  path = [ "abc://test.xyz/test/src", "abc://test.xyz/test/src-mirror" ]

    [[pkg.srcs.hashes]]
    sha256 = "123456789"

    [[pkg.srcs.hashes]]
    md5 = "987654321"

  [[pkg.test]]
  name = "Print Test - POSIX"
  if = [ "${os.group} == \"posix\"", "${os.group} != \"windows\"" ]
  run = 'echo "Hello World!"'

  [[pkg.test]]
  name = "Print Test - Windows"
  if = [ "${os.group} == \"windows\"", "${os.group} != \"posix\"" ]
  run = 'Write-Host "Hello World!"'
