# Github Action to update manifest.yml

name: update manifest.yml

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update manifest.yml
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          echo $GITHUB_WORKSPACE
          echo $GITHUB_SHA

          cd $GITHUB_WORKSPACE

          # Update manifest.yml

          python3 scripts/manifest.py --commit $GITHUB_SHA --repo $GITHUB_REPOSITORY
      
          # Check if manifest.yml has changed
          if [ "$(git diff --name-only HEAD manifest.yml)" != "" ]; then
              echo "manifest.yml has changed"
              # push changes to github
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add manifest.yml 
            git commit -m "Update manifest.yml"
            git push origin main:main 
          fi