# Github Action to update manifest.yml

name: update manifest.yml

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update manifest.yml
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          echo $GITHUB_WORKSPACE
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

          cd $GITHUB_WORKSPACE

          # Update manifest.yml

          python3 scripts/manifest.py --commit $GITHUB_SHA --repo $GITHUB_REPOSITORY